version: '2'

services:

  mysql:
    image: mysql:latest
    tty: true
    stdin_open: true
    ports:
    - "3306:3306"
    env_file:
    - mysql.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - mysqldata:/var/lib/mysql
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  app:
    image: bdr.registries.notifications:devel
    ports:
    - "5000:8888"
    depends_on:
    - mysql
    env_file:
    - mysql.env
    - app.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - appdata:/var/local/bdr.registries.notifications/static
    entrypoint: /usr/bin/tail
    command:  -f /dev/null

volumes:
  mysqldata:
    driver: local
  appdata:
    driver: local
